In [10]:
import numpy as np
import time
from general_robotics_toolbox import fwdkin, Robot
import general_robotics_toolbox as rox

In [11]:
from Arm_Lib import Arm_Device

In [54]:
arm = Arm_Device()

In [55]:
def moveJoint(arm,jnum,ang,speedtime):
    """
    function used to move the specified joint to the given position
    moveJoint(jnum, ang, speedtime) moves joint jnum to position ang degrees in speedtime milliseconds
    function returns nothing
    """
    # call the function to move joint number jnum to ang degrees in speedtime milliseconds
    arm.Arm_serial_servo_write(jnum,ang,speedtime)
    return

In [60]:
def set_angles(arm, angles):
    for joint, angle in enumerate(angles):
        moveJoint(arm, joint, angle, 1000)
set_angles(arm, np.array([60,60,60,60,60,60]))

In [61]:
def initDofbot():
    q = readAllActualJointAngles()
    print(q)
    set_angles(arm, np.ones(shape=(6,1))*90)
    time.sleep(1.1)
    q = readAllActualJointAngles()
    print(q)
    
    H = np.array([
        [0,0,1],
        [0,-1,0],
        [0,-1,0],
        [0,-1,0],
        [-1,0,0]
    ]).T
    
    # define joint lengths
    l0 = 61 * 10**-3
    l1 = 43.5 * 10**-3
    l2 = 82.85 * 10**-3
    l3 = 82.85 * 10**-3
    l4 = 73.85 * 10**-3
    l5 = 54.57 * 10**-3
    
    # position vectors from i-1 to 1
    P = np.array([
        [0, 0, l0],
        [0, 0, l0+l1],
        [0, 0, l0+l1+l2],
        [0, 0, l0+l1+l2+l3],
        [0, 0, l0+l1+l2+l3+l4],
        [0, 0, l0+l1+l2+l3+l4+l5],
    ]).T
    
    joint_type = [0, 0, 0, 0, 0]
    
    return Robot(H, P, joint_type)

dofbot = initDofbot()

[60 60 59 59 60 59]
[89 91 90 90 89 89]


In [62]:
theta = np.random.rand(6,1)*360
print(theta)

[[ 23.24824604]
 [192.11048481]
 [133.20002988]
 [ 77.47179236]
 [250.87865147]
 [114.13986795]]


In [63]:
end_effector_pose = fwdkin(dofbot, theta)
print(end_effector_pose)

R = [[-0.2441  0.9389 -0.2426]
     [-0.7523 -0.0255  0.6583]
     [ 0.6119  0.3432  0.7126]]
p = [-0.1404  0.1275  0.5968]


