In [1]:
import numpy as np
from Robot import UR5Arm
from fwdkin import fwdkin
from invkin import invkin
import math

In [2]:
ex = np.array([1,0,0])
ey = np.array([0,1,0])
ez = np.array([0,0,1])
l0 = 0.061 # base to servo 1
l1 = 0.0435 # servo 1 to servo 2
l2 = 0.08285 # servo 2 to servo 3
l3 = 0.08285 # servo 3 to servo 4
l4 = 0.07385 # servo 4 to servo 5
l5 = 0.05457 # servo 5 to gripper
P01 = ( l0 + l1 ) * ez 
P12 = np.zeros (3) # translation between 1 and 2 frame in 1 frame
P23 = l2 * ex # translation between 2 and 3 frame in 2 frame
P34 = - l3 * ez # translation between 3 and 4 frame in 3 frame
P45 = np.zeros (3) # translation between 4 and 5 frame in 4 frame
P5T = -( l4 + l5 ) * ex 
print(P01,P12,P23,P34,P45,P5T)

[0.     0.     0.1045] [0. 0. 0.] [0.08285 0.      0.     ] [-0.      -0.      -0.08285] [0. 0. 0.] [-0.12842 -0.      -0.     ]


In [3]:
P = np.array([P01, P12, P23, P34, P45, P5T]).T
H = np.array([ez, -ey, -ey, -ey, -ex]).T
print(P,H)
limits = None 
dofbot = UR5Arm(P, H, limits)

[[ 0.       0.       0.08285 -0.       0.      -0.12842]
 [ 0.       0.       0.      -0.       0.      -0.     ]
 [ 0.1045   0.       0.      -0.08285  0.      -0.     ]] [[ 0  0  0  0 -1]
 [ 0 -1 -1 -1  0]
 [ 1  0  0  0  0]]


In [11]:
theta = np.array([90,90,90,90,90])[None].T*math.pi/180
R, P = fwdkin(dofbot, theta)
print(np.around(R,4), np.around(P,4))

[[1.57079633]
 [1.57079633]
 [1.57079633]
 [1.57079633]
 [1.57079633]]
(5, 1)
[[-0. -0. -1.]
 [-0. -1.  0.]
 [-1.  0. -0.]] [0.     0.     0.3986]


In [13]:
theta = np.array([90,90,90,90,90])[None].T*math.pi/180
Rd, Pd = fwdkin(dofbot, theta)
print("here", Pd, Rd)
q0 = np.array([50,50,50,50,50])[None].T*math.pi/180
print(q0)
truth, rv = invkin(dofbot, Rd, Pd, q0)
print(rv)
print(f"before: \n{np.around(R,3), np.around(P,3)}")
print(f"after: \n{rv}")

here [7.81231141e-33 7.03670455e-17 3.98620000e-01] [[-3.69778549e-32 -2.22044605e-16 -1.00000000e+00]
 [-3.33066907e-16 -1.00000000e+00  2.22044605e-16]
 [-1.00000000e+00  3.33066907e-16 -3.69778549e-32]]
[[0.87266463]
 [0.87266463]
 [0.87266463]
 [0.87266463]
 [0.87266463]]
[[-0.5566704  -0.24620194 -0.79341204]
 [-0.66341395  0.70658796  0.24620194]
 [ 0.5         0.66341395 -0.5566704 ]] [0.15816513 0.18849386 0.11814353]
[-5.93641222e-08  1.31662043e-08 -3.82107213e-09  2.14878152e-05
  9.68848149e-05 -7.24935068e-07]
Inverse Kinematics Converged after 166 iterations
[[1.35254194]
 [1.57309424]
 [1.56500276]
 [1.57429191]
 [1.78905071]]
before: 
(array([[-0., -0., -1.],
       [-0., -1.,  0.],
       [-1.,  0., -0.]]), array([0.   , 0.   , 0.399]))
after: 
[[1.35254194]
 [1.57309424]
 [1.56500276]
 [1.57429191]
 [1.78905071]]
