In [1]:
import numpy as np
from Robot import UR5Arm
from fwdkin import fwdkin

In [2]:
ex = np.array([1,0,0])
ey = np.array([0,1,0])
ez = np.array([0,0,1])
l0 = 0.061 # base to servo 1
l1 = 0.0435 # servo 1 to servo 2
l2 = 0.08285 # servo 2 to servo 3
l3 = 0.08285 # servo 3 to servo 4
l4 = 0.07385 # servo 4 to servo 5
l5 = 0.05457 # servo 5 to gripper
P01 = ( l0 + l1 ) * ez 
P12 = np . zeros (3 ,) # translation between 1 and 2 frame in 1 frame
P23 = l2 * ex # translation between 2 and 3 frame in 2 frame
P34 = - l3 * ez # translation between 3 and 4 frame in 3 frame
P45 = np . zeros (3 ,) # translation between 4 and 5 frame in 4 frame
P5T = -( l4 + l5 ) * ex 

In [3]:
P = np.array([P01, P12, P23, P34, P45, P5T]).T
H = np.array([ex, -ey, -ey, -ey, -ey]).T
print(P,H)
limits = None 
dofbot = UR5Arm(P, H, limits)

[[ 0.       0.       0.08285 -0.       0.      -0.12842]
 [ 0.       0.       0.      -0.       0.      -0.     ]
 [ 0.1045   0.       0.      -0.08285  0.      -0.     ]] [[ 1  0  0  0  0]
 [ 0 -1 -1 -1 -1]
 [ 0  0  0  0  0]]


In [4]:
theta = np.array([90,90,90,90,90])
print(fwdkin(dofbot, theta))

[[-0.28369109  0.          0.95891572  0.06568421]
 [-0.85726746 -0.44807362 -0.25361889  0.08820059]
 [ 0.42966484 -0.89399666  0.12711449  0.06029362]
 [ 0.          0.          0.          1.        ]]


In [5]:
theta = np.array([0,0,0,0,0])
print(fwdkin(dofbot, theta))

[[ 1.       0.       0.      -0.04557]
 [ 0.       1.       0.       0.     ]
 [ 0.       0.       1.       0.02165]
 [ 0.       0.       0.       1.     ]]


In [6]:
target = np.random.rand((3,3))

TypeError: 'tuple' object cannot be interpreted as an integer